# Configuration for Label Actions - https://github.com/dessant/label-actions

# Actions taken when the `heated` label is added to issues or pull requests
heated:
  # Post a comment
  comment: >
    The thread has been temporarily locked.
    Please follow our community guidelines.
  # Lock the thread
  lock: true
  # Set a lock reason
  lock-reason: 'too heated'
  # Additionally, add a label to pull requests
  prs:
    label: 'on hold'

# Actions taken when the `heated` label is removed from issues or pull requests
-heated:
  # Unlock the thread
  unlock: true

# Actions taken when the `wontfix` label is removed from issues or pull requests
-wontfix:
  # Reopen the thread
  reopen: true

# Actions taken when the `feature` label is added to issues
feature:
  issues:
    # Post a comment, `{issue-author}` is an optional placeholder
    comment: >
      :wave: @{issue-author}, please use our idea board to request new features.
    # Close the issue
    close: true

# Actions taken when the `wip` label is added to pull requests
wip:
  prs:
    # Add labels
    label:
      - 'on hold'
      - 'needs feedback'

# Actions taken when the `wip` label is removed from pull requests
-wip:
  prs:
    # Add label
    label: 'needs QA'
    # Remove labels
    unlabel:
      - 'on hold'
      - 'needs feedback'

# Actions taken when the `pizzazz` label is added to issues or pull requests
pizzazz:
  # Post comments
  comment:
    - '![](https://i.imgur.com/WuduJNk.jpg)'
    - '![](https://i.imgur.com/1D8yxOo.gif)'
